#cloud-config
ssh_pwauth: true
timezone: "Asia/Seoul"
disable_root: false
hostname: "${hostname}"
users:
  - default
  - name: root
    ssh-authorized-keys:
${ssh_public_key}
  - name: "${ssh_username}"
    gecos: "${ssh_username}"
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    groups: adm,systemd-journal
    primary_group: "${ssh_username}"
    expiredate: '2032-09-01'
    lock_passwd: false
    ssh_authorized_keys:
${ssh_public_key}
write_files:
 - path: /root/.ssh/config
   permissions: '0600'
   owner: root:root
   content: |
     Host *
        IdentityFile /etc/ssh/ssh_host_rsa_key
 - path: /etc/vim/vimrc
   content: |
     set paste
     set ic
     set hlsearch
     colorscheme elflord
   append: true
 - path: /etc/netplan/50-cloud-init.yaml
   content: |
     network:
       version: 2
       ethernets:
         ens3:
           dhcp4: true
           dhcp6: false
         ens4:
           dhcp4: true
           dhcp6: false
         ens5:
           dhcp4: true
           dhcp6: false
         ens6:
           dhcp4: true
           dhcp6: false
ssh_keys:
  rsa_private: |
${ssh_private_key}
packages:
  - vim
  - git 
  - wget
  - python3-pip
  - btop
runcmd:
## Replace Nic 
  - ['netplan', 'apply']
  - ['wget', 'https://raw.githubusercontent.com/huyz/dircolors-solarized/master/dircolors.ansi-light', '-O',  '/root/.dircolors']
package_update: false
package_reboot_if_required: true
